/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Cordinador;
import administra_horarios.*;
import javax.swing.JOptionPane;
import pkAula.*;

/**
 *
 * @author Alonso
 */
public class viewCordAulas extends javax.swing.JFrame {

    /**
     * Creates new form viewCordAulas
     */
    public viewCordAulas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListAulas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLAireAcon = new javax.swing.JLabel();
        jBVerEquipo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLNomMod = new javax.swing.JLabel();
        jLNumAulaMod = new javax.swing.JLabel();
        jLUbicMod = new javax.swing.JLabel();
        jLCapaMod = new javax.swing.JLabel();
        jLAireAconMod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAulasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListAulas);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel1.setText("Aulas");

        jLabel2.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLabel3.setText("Numero de Aula:");

        jLabel4.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLabel4.setText("Ubicacion:");

        jLabel5.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLabel5.setText("Capacidad:");

        jLAireAcon.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLAireAcon.setText("Aire Acondiciondo:");

        jBVerEquipo.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jBVerEquipo.setText("Ver Equipo");
        jBVerEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerEquipoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLNomMod.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLNomMod.setText("Cambiar1");

        jLNumAulaMod.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLNumAulaMod.setText("Cambiar2");

        jLUbicMod.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLUbicMod.setText("Cambiar3");

        jLCapaMod.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLCapaMod.setText("Cambiar4");

        jLAireAconMod.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jLAireAconMod.setText("Cambiar5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 260, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLUbicMod))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLCapaMod))
                            .addComponent(jBVerEquipo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLNomMod))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLNumAulaMod))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLAireAcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLAireAconMod)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLNomMod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLNumAulaMod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLUbicMod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLCapaMod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLAireAcon)
                            .addComponent(jLAireAconMod))
                        .addGap(31, 31, 31)
                        .addComponent(jBVerEquipo)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAulasMouseClicked
        // TODO add your handling code here:
        String numAula = (String)jListAulas.getSelectedValue();
        Aulas aulaActual = Administra_horarios.ListaAulas.get(0);
        for(int i =0; i< Administra_horarios.ListaAulas.size(); i++){
            String temp = Administra_horarios.ListaAulas.get(i).getNumAula();
            if (temp.equals(numAula)){
                aulaActual = Administra_horarios.ListaAulas.get(i);
            }
        }
        
        jLNomMod.setText(aulaActual.getNombre());
        jLNumAulaMod.setText(aulaActual.getNumAula());
        jLUbicMod.setText(aulaActual.getUbicacion());
        jLCapaMod.setText(Integer.toString(aulaActual.getCapaciad()));
        
        String tipoClase = aulaActual.getClass().getCanonicalName();
        if (tipoClase.equals("pkAula.aulaTeoria")){
            aulaTeoria auTeo = (aulaTeoria)aulaActual;
            if(auTeo.getAireAcond() == true){
                jLAireAcon.setText("Aire Acondicionado:");
                jLAireAconMod.setText("Si");
            }
            else{
                jLAireAcon.setText("Aire Acondicionado:");
                jLAireAconMod.setText("No");
            }
            jBVerEquipo.enable(false);
        }
        if (tipoClase.equals("pkAula.aulaPractica")){
            aulaPractica auPra = (aulaPractica)aulaActual;
            jLAireAcon.setText("");
            jLAireAconMod.setText("");
            jBVerEquipo.enable(true);
        }
        Administra_horarios.AulaActual= aulaActual;
    }//GEN-LAST:event_jListAulasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBVerEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerEquipoActionPerformed
        // TODO add your handling code here:
        
        String tipoClase = Administra_horarios.AulaActual.getClass().getCanonicalName();
        if (tipoClase.equals("pkAula.aulaTeoria")){
            JOptionPane.showMessageDialog(null, "Esta Aula no contiene equipo");
        }
        if (tipoClase.equals("pkAula.aulaPractica")){
            new viewCordEquipo().setVisible(true);
            aulaPractica AulaPra = (aulaPractica)Administra_horarios.AulaActual;
            Administra_horarios.ListEquipoActual = AulaPra.getListaEquipo();
            viewCordEquipo.jLNomMod.setText( Administra_horarios.ListEquipoActual.get(0).getNombre());
            viewCordEquipo.jLCantidadMod.setText( String.valueOf(Administra_horarios.ListEquipoActual.get(0).getCantidad()));
            viewCordEquipo.jLTituloMat.setText(AulaPra.getNumAula());
        }
        
        
    }//GEN-LAST:event_jBVerEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCordAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCordAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCordAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCordAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCordAulas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVerEquipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLAireAcon;
    private javax.swing.JLabel jLAireAconMod;
    private javax.swing.JLabel jLCapaMod;
    private javax.swing.JLabel jLNomMod;
    private javax.swing.JLabel jLNumAulaMod;
    private javax.swing.JLabel jLUbicMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JList jListAulas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
