/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Cordinador;

import administra_horarios.metodos;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import pkSemestre.*;
import pkAsignatura.*;
import sun.security.krb5.internal.ccache.CCacheInputStream;
import administra_horarios.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alonso
 */
public class viewCordMaterias extends javax.swing.JFrame {
    
       metodos mtds = new metodos();
    
    /**
     * Creates new form viewCordMaterias
     */
    public viewCordMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListMaterias = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        cpNombre = new javax.swing.JLabel();
        cpModNombre = new javax.swing.JLabel();
        cpCreditos = new javax.swing.JLabel();
        cpModCreditos = new javax.swing.JLabel();
        cpSOPgW = new javax.swing.JLabel();
        cpMatApo = new javax.swing.JLabel();
        cpModSOPgW = new javax.swing.JLabel();
        cpModMatApo = new javax.swing.JLabel();
        jBModificar = new javax.swing.JButton();
        jBVerAulas = new javax.swing.JButton();
        jBHorario = new javax.swing.JButton();
        cpProfesor = new javax.swing.JLabel();
        cpModProfesor = new javax.swing.JLabel();
        jBCerrar = new javax.swing.JButton();
        jBGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListMaterias);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel1.setText("Materias Semestre");

        cpNombre.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpNombre.setText("Nombre:");

        cpModNombre.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModNombre.setText("|");

        cpCreditos.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpCreditos.setText("Creditos:");

        cpModCreditos.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModCreditos.setText("|");

        cpSOPgW.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpSOPgW.setText("SO o PagWeb: ");

        cpMatApo.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpMatApo.setText("Material de Apoyo:");

        cpModSOPgW.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModSOPgW.setText("|");

        cpModMatApo.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModMatApo.setText("|");

        jBModificar.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBVerAulas.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jBVerAulas.setText("Ver Aulas");
        jBVerAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerAulasActionPerformed(evt);
            }
        });

        jBHorario.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jBHorario.setText("Horario");
        jBHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHorarioActionPerformed(evt);
            }
        });

        cpProfesor.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpProfesor.setText("Profesor:");

        cpModProfesor.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModProfesor.setText("|");

        jBCerrar.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        jBGenerar.setText("Generar Horario Semestral");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jBGenerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addComponent(jBCerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jBModificar)
                                        .addGap(12, 12, 12)
                                        .addComponent(jBVerAulas)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBHorario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cpNombre)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpModNombre))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cpSOPgW)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpModSOPgW))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cpCreditos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpModCreditos))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cpMatApo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpModMatApo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cpProfesor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpModProfesor)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCerrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cpNombre)
                                    .addComponent(cpModNombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cpCreditos)
                                    .addComponent(cpModCreditos))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cpSOPgW)
                                    .addComponent(cpModSOPgW))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cpMatApo)
                                    .addComponent(cpModMatApo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cpProfesor)
                                    .addComponent(cpModProfesor))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBModificar)
                                    .addComponent(jBVerAulas)
                                    .addComponent(jBHorario))
                                .addGap(18, 18, 18)
                                .addComponent(jBGenerar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        if(Administra_horarios.AsignaturaSemetreActual == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una materia");
        }
        else{
            new viewCordModificarMat().setVisible(true);
            viewCordModificarMat.cpModNombre.setText(Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig().getNombre());
            viewCordModificarMat.cpModCreditos.setText(String.valueOf(Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig().getCreditos()));
            
            String tipoClase = Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig().getClass().getCanonicalName();
            if (tipoClase.equals("pkAsignatura.Asig_Teorica")){
                Asig_Teorica asigTeo = (Asig_Teorica)Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig();
                viewCordModificarMat.cpSOPgW.setText("Pagina Web:");
                viewCordModificarMat.jTFSOPagWeb.setText(asigTeo.getPaginaWeb());
                viewCordModificarMat.cpMatApo.setText("");
                viewCordModificarMat.jTFMatApoy.show(false);
            
            }
            if (tipoClase.equals("pkAsignatura.Asig_practica")){
                Asig_practica asigPrac = (Asig_practica)Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig();
                viewCordModificarMat.cpSOPgW.setText("Sistema Operativo:");
                viewCordModificarMat.jTFSOPagWeb.setText(asigPrac.getSistemaOperativo());
                viewCordModificarMat.cpMatApo.setText("Material de Apoyo:");
                viewCordModificarMat.jTFMatApoy.show(true);
                viewCordModificarMat.jTFMatApoy.setText(asigPrac.getMaterial());
            }
            int indice = 0;
            for(int i=0; i<Administra_horarios.ListaProfesores.size(); i++){
                viewCordModificarMat.jComboBox1.addItem(Administra_horarios.ListaProfesores.get(i).getNombre());
                if(Administra_horarios.ListaProfesores.get(i).getNombre().equals(Administra_horarios.AsignaturaSemetreActual.getProfesorAsig().getNombre())){
                    indice = i;
                }
            }
            viewCordModificarMat.jComboBox1.setSelectedIndex(indice);
            viewCordModificarMat.indiceProfe = indice;
        
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jListMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMateriasMouseClicked
        // TODO add your handling code here:
        String codigo;
        codigo = (String)jListMaterias.getSelectedValue();
        AsignaturaSemestre sem = mtds.obtenerMateria(codigo);
        cpModNombre.setText(sem.getAsignaturaAsig().getNombre());
        cpModCreditos.setText(Integer.toString(sem.getAsignaturaAsig().getCreditos()));
        cpModProfesor.setText(sem.getProfesorAsig().getNombre());
        
        
        String tipoClase = sem.getAsignaturaAsig().getClass().getCanonicalName();
        if (tipoClase.equals("pkAsignatura.Asig_Teorica")){
            Asig_Teorica asigTeo = (Asig_Teorica)sem.getAsignaturaAsig();
            cpSOPgW.setText("Pagina Web:");
            cpModSOPgW.setText(asigTeo.getPaginaWeb());
            cpMatApo.setText("");
            cpModMatApo.setText("");
        }
        if (tipoClase.equals("pkAsignatura.Asig_practica")){
            Asig_practica asigPrac = (Asig_practica)sem.getAsignaturaAsig();
            cpSOPgW.setText("Sistema Operativo:");
            cpModSOPgW.setText(asigPrac.getSistemaOperativo());
            cpMatApo.setText("Material de Apoyo:");
            cpModMatApo.setText(asigPrac.getMaterial());
        }
        Administra_horarios.AsignaturaSemetreActual = sem;
        
    }//GEN-LAST:event_jListMateriasMouseClicked

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        // TODO add your handling code here:
        new viewCordPrincipal().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHorarioActionPerformed
        // TODO add your handling code here:
        if(Administra_horarios.AsignaturaSemetreActual == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una materia");
        }
        else{
        new viewCordHorarioMat().setVisible(true);
        String codigo = Administra_horarios.AsignaturaSemetreActual.getHorario().get(0).getAulas().getNumAula();
        int indice = 0;
        
        for(int i=0; i< Administra_horarios.ListaAulas.size(); i++){            
            viewCordHorarioMat.jCBAulas.addItem(Administra_horarios.ListaAulas.get(i).getNumAula());
            if (Administra_horarios.ListaAulas.get(i).getNumAula().equals(codigo)){
                indice = i;
            }
        }
        
        viewCordHorarioMat.jCBAulas.setSelectedIndex(indice);
        viewCordHorarioMat.jLNombreMod.setText(Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig().getNombre());
        for(int i=0; i<5; i++){
            String item = (String)viewCordHorarioMat.jCBDia.getItemAt(i);
            if (item.equals(Administra_horarios.AsignaturaSemetreActual.getHorario().get(0).getDia())){
                viewCordHorarioMat.jCBDia.setSelectedIndex(i);
                break;
            }
        }
        
        viewCordHorarioMat.spHoraIni.setValue(Administra_horarios.AsignaturaSemetreActual.getHorario().get(0).getHoraInicial());
        viewCordHorarioMat.spMinIni.setValue(Administra_horarios.AsignaturaSemetreActual.getHorario().get(0).getMinutosInicial());
        viewCordHorarioMat.spHoraFin.setValue(Administra_horarios.AsignaturaSemetreActual.getHorario().get(0).getHoraFinal());
        viewCordHorarioMat.spMinFin.setValue(Administra_horarios.AsignaturaSemetreActual.getHorario().get(0).getMinutosFinal());
        viewCordHorarioMat.jLTitulo.setText(Administra_horarios.AsignaturaSemetreActual.getAsignaturaAsig().getNombre());
        
        Administra_horarios.horarioAatual = Administra_horarios.AsignaturaSemetreActual.getHorario();
        viewCordHorarioMat.indice = 0;
        }
    }//GEN-LAST:event_jBHorarioActionPerformed

    private void jBVerAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerAulasActionPerformed
        // TODO add your handling code here:
        new viewCordAulas().setVisible(true);
        mtds.generarListaAulas(Administra_horarios.ListaAulas);
    }//GEN-LAST:event_jBVerAulasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCordMaterias().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpCreditos;
    private javax.swing.JLabel cpMatApo;
    private javax.swing.JLabel cpModCreditos;
    private javax.swing.JLabel cpModMatApo;
    private javax.swing.JLabel cpModNombre;
    private javax.swing.JLabel cpModProfesor;
    private javax.swing.JLabel cpModSOPgW;
    private javax.swing.JLabel cpNombre;
    private javax.swing.JLabel cpProfesor;
    private javax.swing.JLabel cpSOPgW;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBGenerar;
    private javax.swing.JButton jBHorario;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBVerAulas;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JList jListMaterias;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
