/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Cordinador;

/**
 *
 * @author Alonso
 */
public class viewCordMaterias extends javax.swing.JFrame {

    /**
     * Creates new form viewCordMaterias
     */
    public viewCordMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        cpNombre = new javax.swing.JLabel();
        cpModNombre = new javax.swing.JLabel();
        cpCreditos = new javax.swing.JLabel();
        cpModCreditos = new javax.swing.JLabel();
        cpSOPgW = new javax.swing.JLabel();
        cpMatApo = new javax.swing.JLabel();
        cpModSOPgW = new javax.swing.JLabel();
        cpModMatApo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cpProfesor = new javax.swing.JLabel();
        cpModProfesor = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel1.setText("Materias Semestre");

        cpNombre.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpNombre.setText("Nombre:");

        cpModNombre.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModNombre.setText("modifica");

        cpCreditos.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpCreditos.setText("Creditos:");

        cpModCreditos.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModCreditos.setText("modifica2");

        cpSOPgW.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpSOPgW.setText("SO o PagWeb: ");

        cpMatApo.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpMatApo.setText("Material de Apoyo:");

        cpModSOPgW.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModSOPgW.setText("modiica3");

        cpModMatApo.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModMatApo.setText("modifica4");

        jButton1.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jButton1.setText("Modificar");

        jButton2.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jButton2.setText("Ver Aulas");

        jButton3.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        jButton3.setText("Horario");

        cpProfesor.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpProfesor.setText("Profesor:");

        cpModProfesor.setFont(new java.awt.Font("High Tower Text", 0, 16)); // NOI18N
        cpModProfesor.setText("modifica5");

        jButton4.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jButton4.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpModNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpSOPgW)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpModSOPgW))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpCreditos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpModCreditos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpMatApo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpModMatApo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpProfesor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpModProfesor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(0, 42, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpNombre)
                            .addComponent(cpModNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpCreditos)
                            .addComponent(cpModCreditos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpSOPgW)
                            .addComponent(cpModSOPgW))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpMatApo)
                            .addComponent(cpModMatApo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpProfesor)
                            .addComponent(cpModProfesor))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCordMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCordMaterias().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpCreditos;
    private javax.swing.JLabel cpMatApo;
    private javax.swing.JLabel cpModCreditos;
    private javax.swing.JLabel cpModMatApo;
    private javax.swing.JLabel cpModNombre;
    private javax.swing.JLabel cpModProfesor;
    private javax.swing.JLabel cpModSOPgW;
    private javax.swing.JLabel cpNombre;
    private javax.swing.JLabel cpProfesor;
    private javax.swing.JLabel cpSOPgW;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
